---
- name: Provision
  hosts: all
  remote_user: archdri
  become: true

  tasks:
  - name: Añadir repositorio de python 3.6
    become: true
    apt_repository: repo=ppa:deadsnakes/ppa state=present

  - name: Actualizar sistema
    become: true
    command: sudo apt-get update

  - name: Instalar Python 3.6
    become: true
    apt: pkg=python3.6 state=present

  - name: Cambio version de python
    command: sudo ln -sfn /usr/bin/python3.6 /usr/bin/python

  - name: Instalacion de pip3
    become: true
    command: sudo apt-get -y install python3-pip

  - name: Clonar mi repositorio de GitHub
    git: repo=https://github.com/adriordi/proyectoIV.git dest=proyectoIV/ force=yes

  - name: Instalar proyecto
    command: make install