language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- make test
deploy:
  provider: heroku
  api_key:
    secure: ZRr6cE1L/txpTmMzivAUg3Hz1SuyqsjnnvKPc4Tp9nnuy+khJX+0H/4k9gv7g7oRAeOvqcQxrG66oHbZeJrxAWCNM+UnP+fl6JMDqHpOTFHKMacq5OnCntY1/IU3v2l3wcrN018VN1OetJnYdu/cADaQnPhmY7DjzrGq/Qti8cEguiGDDanL0FqHtHLRiBMF1yPFkgtnhstjMY4XimL3tFJAFUL3xelMnhE0mKTn7pQejoqdWYiuu8U+AQB1VmkmxsuSorYcZtNVOWCPshM3zADiBOg5FX4NLzfwXOMjIcSRKiAXqyxOlTGZnxEUKKyIE+WELniFYTzDmS/a9IuZRoPsv1+3SS0JdGZxkEOw15q2Mi2kVpoeNGHicdfZ8vi5hySRPqZY0bR6b+YR/MsheFZu/k1I2OFBLb1uBh3OAhthV1exJstTk3Wtsw9v6uDDPnODGK7CkK7lQGhHf9/nSP5VYKj2Qi2VHqkj+dlISj35L5yFZoJhCozU8b04SiVW9+dclAomf4fs+aPX3vMRaWgP5zeJD1VJIpnYR28kaPmaUwoUAtQxdQAOv7xHmx0UTitVa+s83clbjN9IfjFADas+VtmmYMi6XXp+1bkagilJR+UlLKcbd9qocdJ062BtIOG7Fx38vSGJtVPN6er8E3XgyT/18RvVdIIKyHY61nY=
  app: workwaitqueue
