language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- make test
deploy:
  provider: heroku
  api_key:
    secure: VWlI/7O7yQB51TPzGyIEIKiBNLZIOAIroAXBK1GTiJECJIaKxd6YBPrRqa98ZR1msC0rr1VsgElT0l6/4B819LdOsc1bVJ3p2VmrgDIHK1ZctLGkShewI56TOPAdrzsHR0zkVoTmTboEdWS/72XIZdunwhcNldvCUABpWFX+5BQ5s+/MKpTrwnSoyOh4CD04gVEMKSxVz0eC8pNVlaJFR71OmzIMRw9f6Z7KQ27VAYAM54k5/woFA6DnVsQp2aO4fiRwp6ssQOAP/yTNOTcNWEPpmtM4zQNH7MIuMFhJFh46cj2mG06HfBw5pFTLHyjLyo1nZCDa/ez0u9fVKJ9Kp5KXZSyiWzA3/T9jU4wLHuTzcZXElUpxrXnh1PKJvODDo169Izqhfei3RlbfIL1wafuq4NPRVtwpEb1wpV30zkqEgsnJbAEzT+SpQ5ca6eSSgB6qE9sYhbuOGlGsBMB5HKHtXLliYNNKA1WDZOBbYiv1oWE6cdnb+1rsZ4a3rsmmTOa4lboRJUB6caN4ZrPNAmr/oL9WrN1b/arWC+xKLgzwDbjxxoLhk0WcKSYo3B88fkakIWn0o/wba9n8MMc/fx6aYTAvs770R9oj+On8FXfBdfG7IJf7/f5trGkIkExnsPJAbJ8cd3G8RrlpKb6c8kHBSq9g753n9ts2HQey8MI=
  app: workwaitqueue
