language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- make test
deploy:
  provider: heroku
  api_key:
    secure: rXCm7giivrYZ4sEExHR+jr1W0tH3R2Kn2Jb1HgG/EaWFpcnRdavtc2Qdi8JyOjxAFSk/k94/4xLy39HUKpo0NN8RFUjln5q5KgOanhz1qo5ZPe6JePkaIwgo7bKzqOSp8E0oRQDjX1xk9nnOwHIigyWeZXhH4Y8PYS8lEJnGj3zbX2ak90wvqjppNVWWOW+28nB6f1sh6QGzR/SNPK4pRiHNPhKhnahMEEEsk6j6Ab76ZjQiwi4kA0lmhMH1zl59zuNEPOCy+jlzcpTN9nNygo1zstvlWHimZqryFgNgRLpPyMe0s/vGVT7aDeqsnfxQxjVEhn5iMz/OJd3Fn3WtwYCzDjuJIee7gjJgfQvSHirGKD3zRWFgZV5jqJwa/dFF8nAEQaiJnwUlqAaV0P99Ka81FIo4uXDKWD1h+UYoOUd3M7J0mtXwIYvctWsRufSMof05a8wyJqrwMrJji6kHt8Zh6+lp2JARgJjOBnelHYc7s8vFij/H+JJURNJorT7xyu/Xf68xZzrGdMgd1s0HYCTttQFd4LprIlbGergN3w+xYOXw96prCmPqOUWCitCkxJPH7L3LOVKBDdDX5a1kBQUJVpfS5OvlmR7ylSNCEquMXBph+QQZj8v1rmejKRj8CQsIqFH1Ky0tFnLhZt0KFmXnp75XLEJ6u6G6sqUxAt8=
  app: workwaitqueue
